export { default as challenge1 } from './001'
export { default as challenge2 } from './002'
export { default as challenge3 } from './003'
export { default as challenge4 } from './004'
export { default as challenge5 } from './005'
export { default as challenge6 } from './006'
