name: Generate readme

on:
  push:
    branches: [master]

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Run Script
        run: |
          npm ci
          npm run generate-readme
      - name: Commit changes
        run: |
          git config --global  user.name felipeog
          git config --global  user.email 17603069+felipeog@users.noreply.github.com
          git commit -am "Update readme"
          git push
