name: Test

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: 'Clean install dependencies'
        run: npm ci

      - name: 'Test'
        run: npm test

      - name: 'Upload targets images'
        uses: actions/upload-artifact@v3
        with:
          name: targets-images
          path: shared/targetsImages

      - name: 'Upload solutions images'
        uses: actions/upload-artifact@v3
        with:
          name: solutions-images
          path: shared/solutionsImages
